[[headers]]
  for = "/*"
  [headers.values]
   Content-Security-Policy = "default-src 'self'; script-src 'self' https://www.googletagmanager.com https://www.google-analytics.com; style-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com; font-src 'self' https://cdnjs.cloudflare.com; img-src 'self' data: https://res.cloudinary.com https://www.google.com; connect-src 'self' https://*.supabase.co https://www.google-analytics.com; frame-src https://www.google.com https://www.google.com/maps https://maps.google.com; frame-ancestors 'self';"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    Cross-Origin-Opener-Policy = "same-origin"
    Referrer-Policy = "strict-origin-when-cross-origin"
